<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-92RGEGD" failures="1" tests="1" name="Test" time="8.499" errors="0" timestamp="2022-04-30T12:37:04 IST">
  <testcase classname="tests.calTests" name="divTest" time="1.326">
    <failure type="java.lang.AssertionError" message="expected [20] but found [458]">
      <![CDATA[java.lang.AssertionError: expected [20] but found [458]
at tests.calTests.divTest(calTests.java:191)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- divTest -->
</testsuite> <!-- Test -->
